name: DISCORD QUOTE SENDER PROGRAMMING
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 21 * * *'
jobs:
  main:
    name: DISCORD QUOTE SENDER PROGRAMMING
    runs-on: ubuntu-latest
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v3
      - name: 'GET QUOTE'
        shell: pwsh
        run: |
          $object = Get-Content .\.github\workflows\PROGRAMMING_QUOTES.json -Raw | ConvertFrom-Json | Get-Random
          Write-Output "QUOTE=$($object.quote.replace("`n"," ").replace("`r"," ").replace(","," "))" >> $env:GITHUB_ENV
          Write-Output "AUTHOR=$($object.author)" >> $env:GITHUB_ENV
      - name: 'SEND QUOTE'
        uses: appleboy/discord-action@master
        with:
          webhook_id: "${{ secrets.WEBHOOK_ID }}"
          webhook_token: "${{ secrets.WEBHOOK_TOKEN }}"
          args: "@here\n> ″*${{ env.QUOTE }}*″ — ${{ env.AUTHOR }}"
